openapi: 3.0.1
info:
  title: DBrowser
  description: Database Browser as a RESTful Web Service
  version: 1.0.0
servers:
- url: http://localhost:8080/
tags:
- name: connection
  description: DB connection information
paths:

  /connections:
    post:
      tags:
      - connection
      summary: Add new DB connection information
      requestBody:
        description: DB connection information that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connection'
        required: true
      responses:
        200:
          description: successful operation
    put:
      tags:
      - connection
      summary: Update existing DB connection information
      requestBody:
        description: DB connection information that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connection'
        required: true
      responses:
        200:
          description: successful operation
    get:
      tags:
      - connection
      summary: Get all DB connection information
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connection'

  /connections/{connectionId}:
    get:
      tags:
      - connection
      summary: Get DB Connection by id
      description: Returns a DB Connection object
      parameters:
      - name: connectionId
        in: path
        description: ID of Connection to return
        required: true
        schema:
          type: integer
          format: int64
          example: 123
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
    delete:
      tags:
      - connection
      summary: Deletes a DB Connection
      parameters:
      - name: connectionId
        in: path
        description: ID of Connection to delete
        required: true
        schema:
          type: integer
          format: int64
          example: 123
      responses:
        200:
          description: successful operation

  /connections/{connectionId}/schemas:
    get:
      tags:
      - connection
      summary: Get all schemas
      description: Returns an array of schemas
      parameters:
      - name: connectionId
        in: path
        description: ID of Connection to return
        required: true
        schema:
          type: integer
          format: int64
          example: 123
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /connections/{connectionId}/schemas/{schema}/tables:
    get:
      tags:
      - connection
      summary: Get all tables of a schema
      description: Returns an array of tables of a schema
      parameters:
      - name: connectionId
        in: path
        description: ID of Connection to return
        required: true
        schema:
          type: integer
          format: int64
          example: 123
      - name: schema
        in: path
        description: Name of Schema to use
        required: true
        schema:
          type: string
          example: PUBLIC
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /connections/{connectionId}/schemas/{schema}/tables/{table}/columns:
    get:
      tags:
      - connection
      summary: Get all column information of a table
      description: Returns an array of column information of a table
      parameters:
      - name: connectionId
        in: path
        description: ID of Connection to return
        required: true
        schema:
          type: integer
          format: int64
          example: 123
      - name: schema
        in: path
        description: Name of Schema to use
        required: true
        schema:
          type: string
          example: PUBLIC
      - name: table
        in: path
        description: Name of Table to use
        required: true
        schema:
          type: string
          example: DATABASE_CONNECTION
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /connections/{connectionId}/schemas/{schema}/tables/{table}/data:
    get:
      tags:
      - connection
      summary: Get all data of a table
      description: Returns an array of data of a table
      parameters:
      - name: connectionId
        in: path
        description: ID of Connection to return
        required: true
        schema:
          type: integer
          format: int64
          example: 123
      - name: schema
        in: path
        description: Name of Schema to use
        required: true
        schema:
          type: string
          example: PUBLIC
      - name: table
        in: path
        description: Name of Table to use
        required: true
        schema:
          type: string
          example: DATABASE_CONNECTION
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /connections/{connectionId}/schemas/{schema}/tables/{table}/statistics:
    get:
      tags:
      - connection
      summary: Get all statistics of a table
      description: Returns all statistics of a table
      parameters:
      - name: connectionId
        in: path
        description: ID of Connection to return
        required: true
        schema:
          type: integer
          format: int64
          example: 123
      - name: schema
        in: path
        description: Name of Schema to use
        required: true
        schema:
          type: string
          example: PUBLIC
      - name: table
        in: path
        description: Name of Table to use
        required: true
        schema:
          type: string
          example: DATABASE_CONNECTION
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TableStatistics'

  /connections/{connectionId}/schemas/{schema}/tables/{table}/column/{column}/statistics:
    get:
      tags:
      - connection
      summary: Get all statistics of a table
      description: Returns all statistics of a table
      parameters:
      - name: connectionId
        in: path
        description: ID of Connection to return
        required: true
        schema:
          type: integer
          format: int64
          example: 123
      - name: schema
        in: path
        description: Name of Schema to use
        required: true
        schema:
          type: string
          example: PUBLIC
      - name: table
        in: path
        description: Name of Table to use
        required: true
        schema:
          type: string
          example: DATABASE_CONNECTION
      - name: column
        in: path
        description: Name of Column to use
        required: true
        schema:
          type: string
          example: ID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ColumnStatistics'

components:
  schemas:

    Connection:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
        name:
          type: string
          description: Connection Name
          example: test
        databaseName:
          type: string
          description: Database Name
          example: target/db/testdb
        username:
          type: string
          description: Username
          example: SA
        password:
          type: string
          description: Password
          example: ""

    ColumnStatistics:
      type: object
      properties:
        min:
          type: number
          format: double
        max:
          type: number
          format: double
        average:
          type: number
          format: double
        median:
          type: number
          format: double

    TableStatistics:
      type: object
      properties:
        rows:
          type: integer
          format: int64
        columns:
          type: integer
          format: int64
